-- ============================================================
-- Seed 002 - Catálogo de exercícios base
-- ============================================================

INSERT INTO dbo.exercicio (nome, grupo_muscular, equipamento) VALUES

-- PEITO
('Supino Reto com Barra','Peito','Barra'),
('Supino Inclinado com Barra','Peito','Barra'),
('Supino Declinado com Barra','Peito','Barra'),
('Supino Reto com Halteres','Peito','Halteres'),
('Supino Inclinado Halteres','Peito','Halteres'),
('Supino Declinado Halteres','Peito','Halteres'),
('Crucifixo com Halteres','Peito','Halteres'),
('Crucifixo Inclinado','Peito','Halteres'),
('Crucifixo Declinado','Peito','Halteres'),
('Crossover no Cabo','Peito','Cabo'),
('Crossover Alto','Peito','Cabo'),
('Crossover Baixo','Peito','Cabo'),
('Peck Deck (Voador)','Peito','Máquina'),
('Flexão de Braço','Peito','Peso corporal'),
('Flexão Inclinada','Peito','Peso corporal'),
('Flexão Declinada','Peito','Peso corporal'),

-- COSTAS
('Puxada Frontal','Costas','Cabo'),
('Puxada Atrás','Costas','Cabo'),
('Puxada Neutra','Costas','Cabo'),
('Puxada Supinada','Costas','Cabo'),
('Remada Curvada com Barra','Costas','Barra'),
('Remada Unilateral Halter','Costas','Halteres'),
('Remada Baixa','Costas','Cabo'),
('Remada Sentada','Costas','Máquina'),
('Remada Cavalinho','Costas','Máquina'),
('Remada no T-Bar','Costas','Barra'),
('Pulldown no Cabo','Costas','Cabo'),
('Pullover no Cabo','Costas','Cabo'),
('Pullover com Halter','Costas','Halteres'),
('Levantamento Terra','Costas','Barra'),
('Barra Fixa','Costas','Peso corporal'),
('Barra Fixa Supinada','Costas','Peso corporal'),

-- PERNAS
('Agachamento Livre','Pernas','Barra'),
('Agachamento Frontal','Pernas','Barra'),
('Agachamento no Smith','Pernas','Máquina'),
('Agachamento Búlgaro','Pernas','Halteres'),
('Hack Machine','Pernas','Máquina'),
('Leg Press 45°','Pernas','Máquina'),
('Cadeira Extensora','Pernas','Máquina'),
('Mesa Flexora','Pernas','Máquina'),
('Cadeira Flexora','Pernas','Máquina'),
('Stiff com Barra','Pernas','Barra'),
('Levantamento Terra Romeno','Pernas','Barra'),
('Avanço com Halteres','Pernas','Halteres'),
('Passada Caminhando','Pernas','Halteres'),
('Afundo no Smith','Pernas','Máquina'),
('Elevação Pélvica','Pernas','Barra'),
('Elevação Pélvica Unilateral','Pernas','Peso corporal'),
('Glúteo no Cabo','Pernas','Cabo'),
('Abdução de Quadril','Pernas','Máquina'),
('Adução de Quadril','Pernas','Máquina'),
('Panturrilha em Pé','Pernas','Máquina'),
('Panturrilha Sentado','Pernas','Máquina'),
('Panturrilha no Leg Press','Pernas','Máquina'),
('Sissy Squat','Pernas','Peso corporal'),

-- OMBRO
('Desenvolvimento com Barra','Ombro','Barra'),
('Desenvolvimento Halteres','Ombro','Halteres'),
('Desenvolvimento Arnold','Ombro','Halteres'),
('Desenvolvimento no Smith','Ombro','Máquina'),
('Desenvolvimento na Máquina','Ombro','Máquina'),
('Elevação Lateral','Ombro','Halteres'),
('Elevação Lateral Unilateral','Ombro','Halteres'),
('Elevação Lateral no Cabo','Ombro','Cabo'),
('Elevação Frontal','Ombro','Halteres'),
('Elevação Frontal com Barra','Ombro','Barra'),
('Encolhimento de Ombros','Ombro','Halteres'),
('Remada Alta','Ombro','Barra'),
('Crucifixo Inverso','Ombro','Halteres'),
('Face Pull','Ombro','Cabo'),

-- BÍCEPS
('Rosca Direta com Barra','Bíceps','Barra'),
('Rosca Alternada Halteres','Bíceps','Halteres'),
('Rosca Martelo','Bíceps','Halteres'),
('Rosca Martelo no Cabo','Bíceps','Cabo'),
('Rosca Scott','Bíceps','Máquina'),
('Rosca Scott com Barra W','Bíceps','Barra'),
('Rosca Concentrada','Bíceps','Halteres'),
('Rosca Concentrada Unilateral','Bíceps','Halteres'),
('Rosca no Cabo','Bíceps','Cabo'),
('Rosca Inversa','Bíceps','Barra'),
('Rosca 21','Bíceps','Barra'),
('Rosca Spider','Bíceps','Halteres'),

-- TRÍCEPS
('Tríceps Testa com Barra','Tríceps','Barra'),
('Tríceps Francês Halteres','Tríceps','Halteres'),
('Tríceps Francês Unilateral','Tríceps','Halteres'),
('Tríceps Pulley','Tríceps','Cabo'),
('Tríceps Corda','Tríceps','Cabo'),
('Tríceps Inverso no Cabo','Tríceps','Cabo'),
('Tríceps na Máquina','Tríceps','Máquina'),
('Tríceps Coice','Tríceps','Halteres'),
('Mergulho no Banco','Tríceps','Peso corporal'),
('Mergulho nas Paralelas','Tríceps','Peso corporal'),
('Tríceps Banco','Tríceps','Peso corporal'),
('Supino Fechado','Tríceps','Barra'),

-- ABDÔMEN
('Abdominal Crunch','Abdômen','Peso corporal'),
('Abdominal Infra','Abdômen','Peso corporal'),
('Abdominal Oblíquo','Abdômen','Peso corporal'),
('Abdominal Bicicleta','Abdômen','Peso corporal'),
('Abdominal Remador','Abdômen','Peso corporal'),
('Abdominal na Polia','Abdômen','Cabo'),
('Abdominal na Máquina','Abdômen','Máquina'),
('Prancha','Abdômen','Peso corporal'),
('Prancha Lateral','Abdômen','Peso corporal'),
('Prancha com Elevação de Pernas','Abdômen','Peso corporal'),
('Elevação de Pernas','Abdômen','Peso corporal'),
('Mountain Climber','Abdômen','Peso corporal'),

-- CARDIO
('Esteira','Cardio','Máquina'),
('HIIT na Esteira','Cardio','Máquina'),
('Bicicleta Ergométrica','Cardio','Máquina'),
('Elíptico','Cardio','Máquina'),
('Escada','Cardio','Máquina'),
('Air Bike','Cardio','Máquina'),
('Remo Ergométrico','Cardio','Máquina'),
('Corrida ao Ar Livre','Cardio','Peso corporal'),
('Corda de Pular','Cardio','Peso corporal'),
('Polichinelo','Cardio','Peso corporal'),
('Burpee','Cardio','Peso corporal');
