import api from './api'

export const listar       = (params = {}) => api.get('/dieta', { params }).then(r => r.data)
export const buscarPorId  = (id)          => api.get(`/dieta/${id}`).then(r => r.data)
export const criar        = (dados)       => api.post('/dieta', dados).then(r => r.data)
export const atualizar    = (id, dados)   => api.put(`/dieta/${id}`, dados).then(r => r.data)
export const buscarMeuPlano = ()          => api.get('/dieta/meu-plano').then(r => r.data)
export const clonar           = (id, idUsuario) => api.post(`/dieta/${id}/clonar`, { id_usuario: idUsuario }).then(r => r.data)
export const toggleAtivo          = (id)         => api.patch(`/dieta/${id}/toggle`).then(r => r.data)
export const deletarPlano         = (id)         => api.delete(`/dieta/${id}`).then(r => r.data)
export const atualizarStatusPlano = (id, status) => api.patch(`/dieta/${id}/status`, { status }).then(r => r.data)
export const dadosAluno             = (idUsuario)     => api.get(`/dieta/aluno/${idUsuario}/dados`).then(r => r.data)
export const buscarMeuPlanoAndamento = ()             => api.get('/dieta/meu-plano-andamento').then(r => r.data)
export const buscarMinhaSolicitacao  = ()             => api.get('/dieta/solicitacao').then(r => r.data)
export const solicitarDieta         = (dados)         => api.post('/dieta/solicitacao', dados).then(r => r.data)
export const listarSolicitacoes     = (status)        => api.get('/dieta/solicitacoes', { params: status ? { status } : {} }).then(r => r.data)
export const atualizarStatusSolicitacao = (id, status) => api.patch(`/dieta/solicitacoes/${id}/status`, { status }).then(r => r.data)
