const { Router } = require('express')
const alunos       = require('../controllers/admin.alunos.controller')
const avaliacoes   = require('../controllers/admin.avaliacao.controller')
const questionario = require('../controllers/admin.questionario.controller')
const personais        = require('../controllers/admin.personais.controller')
const nutricionistas   = require('../controllers/admin.nutricionistas.controller')
const dashboard        = require('../controllers/admin.dashboard.controller')
const usuarios         = require('../controllers/admin.usuarios.controller')
const planos           = require('../controllers/admin.planos.controller')
const assinaturas      = require('../controllers/admin.assinaturas.controller')
const evolucao         = require('../controllers/admin.evolucao.controller')
const integracoes      = require('../controllers/admin.integracoes.controller')
const logs             = require('../controllers/admin.logs.controller')

const router = Router()

router.get('/dashboard', dashboard.resumo)

router.get('/questionario',      questionario.listar)
router.get('/questionario/:id',  questionario.buscar)
router.post('/questionario',     questionario.criar)
router.put('/questionario/:id',  questionario.atualizar)

router.get('/alunos',                    alunos.listar)
router.post('/alunos',                   alunos.criar)
router.get('/alunos/:id',                alunos.buscar)
router.put('/alunos/:id',                alunos.atualizar)
router.patch('/alunos/:id/toggle-ativo', alunos.toggleAtivo)

router.get('/avaliacoes',                  avaliacoes.listar)
router.get('/avaliacoes/:id',              avaliacoes.buscar)
router.post('/avaliacoes/:id/reatribuir',  avaliacoes.reatribuir)

router.get('/personais',                    personais.listar)
router.post('/personais',                   personais.criar)
router.get('/personais/:id',                personais.buscar)
router.put('/personais/:id',                personais.atualizar)
router.patch('/personais/:id/toggle-ativo', personais.toggleAtivo)

router.get('/nutricionistas',                    nutricionistas.listar)
router.post('/nutricionistas',                   nutricionistas.criar)
router.get('/nutricionistas/:id',                nutricionistas.buscar)
router.put('/nutricionistas/:id',                nutricionistas.atualizar)
router.patch('/nutricionistas/:id/toggle-ativo', nutricionistas.toggleAtivo)

router.get('/usuarios/verificar-email',    usuarios.verificarEmail)
router.get('/usuarios',                    usuarios.listar)
router.post('/usuarios',                   usuarios.criar)
router.get('/usuarios/:id',                usuarios.buscar)
router.put('/usuarios/:id',                usuarios.atualizar)
router.patch('/usuarios/:id/toggle-ativo', usuarios.toggleAtivo)

router.get('/planos',                    planos.listar)
router.post('/planos',                   planos.criar)
router.get('/planos/:id',                planos.buscar)
router.put('/planos/:id',                planos.atualizar)
router.patch('/planos/:id/toggle-ativo', planos.toggleAtivo)

router.get('/assinaturas',                  assinaturas.listar)
router.post('/assinaturas',                 assinaturas.criar)
router.get('/assinaturas/:id',              assinaturas.buscar)
router.put('/assinaturas/:id',              assinaturas.atualizar)
router.patch('/assinaturas/:id/cancelar',   assinaturas.cancelar)

router.get('/evolucao-alunos',                        evolucao.listarAlunos)
router.get('/evolucao-alunos/:id/resumo',             evolucao.resumo)
router.get('/evolucao-alunos/:id/sessoes',            evolucao.sessoes)
router.get('/evolucao-alunos/:id/medidas',            evolucao.listarMedidas)
router.get('/evolucao-alunos/:id/carga',              evolucao.historicoExercicio)
router.get('/evolucao-alunos/:id/exercicios',         evolucao.exercicios)
router.get('/evolucao-alunos/:id/fotos',              evolucao.listarFotos)
router.get('/evolucao-alunos/:id/analise-ia',         evolucao.buscarAnalise)
router.post('/evolucao-alunos/:id/analise-ia',        evolucao.analiseIA)

router.get('/integracoes/whatsapp/status',            integracoes.status)
router.get('/integracoes/whatsapp/logs',              integracoes.listarLogs)
router.post('/integracoes/whatsapp/teste',            integracoes.enviarTeste)
router.post('/integracoes/whatsapp/cron/:tipo',       integracoes.executarCronManual)

const config    = require('../controllers/admin.configuracao.controller')
const pagamento = require('../controllers/admin.pagamento.controller')
const desafios = require('../controllers/admin.desafio.controller')
router.get('/pagamentos/resumo',                pagamento.resumo)
router.get('/pagamentos/pendentes',             pagamento.pendentes)
router.get('/pagamentos/historico',             pagamento.historico)
router.post('/pagamentos',                      pagamento.criar)
router.patch('/pagamentos/:id/pagar',           pagamento.pagar)
router.patch('/pagamentos/:id/cancelar',        pagamento.cancelar)
router.post('/assinaturas/:id/gerar-cobranca',  pagamento.gerarCobranca)

router.get('/configuracoes',                    config.getAll)
router.put('/configuracoes/:categoria',        config.salvarCategoria)

router.get('/desafios',                    desafios.listar)
router.post('/desafios',                   desafios.criar)
router.patch('/desafios/:id/toggle-ativo', desafios.toggleAtivo)

router.get('/logs/auditoria',                       logs.listarAuditoria)
router.get('/logs/whatsapp',                        logs.listarWhatsapp)
router.get('/logs/ultima-modificacao/:entidade/:id', logs.ultimaModificacao)

module.exports = router
