const router = require('express').Router()
const ctrl = require('../controllers/dieta.controller')

router.get('/',           ctrl.listar)
router.post('/',          ctrl.criar)
router.get('/meu-plano',        ctrl.meuPlano)
router.get('/meu-plano-andamento', ctrl.meuPlanoAndamento)
router.get('/solicitacao',      ctrl.minhaSolicitacao)
router.post('/solicitacao',     ctrl.solicitarDieta)
router.get('/solicitacoes',     ctrl.listarSolicitacoes)
router.patch('/solicitacoes/:id/status', ctrl.atualizarStatusSolicitacao)
router.get('/aluno/:id/dados',  ctrl.dadosAluno)
router.get('/:id',              ctrl.buscar)
router.put('/:id',              ctrl.atualizar)
router.patch('/:id/toggle',     ctrl.toggleAtivo)
router.patch('/:id/status',     ctrl.atualizarStatusPlano)
router.delete('/:id',           ctrl.deletar)
router.post('/:id/clonar',      ctrl.clonar)

module.exports = router
